Traceback (most recent call last):
  File "/Volumes/zorg/mb312/.virtualenvs/lis-lession/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Volumes/zorg/mb312/.virtualenvs/lis-lession/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Volumes/zorg/mb312/.virtualenvs/lis-lession/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Volumes/zorg/mb312/.virtualenvs/lis-lession/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Volumes/zorg/mb312/.virtualenvs/lis-lession/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Volumes/zorg/mb312/.virtualenvs/lis-lession/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Volumes/zorg/mb312/.virtualenvs/lis-lession/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
lprs = Table.read_table('./all-lprs.csv.gz', compression='gzip', sep=',')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m lprs [38;5;241m=[39m [43mTable[49m[38;5;241;43m.[39;49m[43mread_table[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m./all-lprs.csv.gz[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mcompression[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mgzip[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43msep[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m,[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/Library/Python/3.8/lib/python/site-packages/datascience/tables.py:137[0m, in [0;36mTable.read_table[0;34m(cls, filepath_or_buffer, *args, **vargs)[0m
[1;32m    135[0m [38;5;28;01mexcept[39;00m [38;5;167;01mAttributeError[39;00m:
[1;32m    136[0m     [38;5;28;01mpass[39;00m
[0;32m--> 137[0m df [38;5;241m=[39m [43mpandas[49m[38;5;241;43m.[39;49m[43mread_csv[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mvargs[49m[43m)[49m
[1;32m    138[0m [38;5;28;01mreturn[39;00m [38;5;28mcls[39m[38;5;241m.[39mfrom_df(df)

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py:311[0m, in [0;36mdeprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    305[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(args) [38;5;241m>[39m num_allow_args:
[1;32m    306[0m     warnings[38;5;241m.[39mwarn(
[1;32m    307[0m         msg[38;5;241m.[39mformat(arguments[38;5;241m=[39marguments),
[1;32m    308[0m         [38;5;167;01mFutureWarning[39;00m,
[1;32m    309[0m         stacklevel[38;5;241m=[39mstacklevel,
[1;32m    310[0m     )
[0;32m--> 311[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py:586[0m, in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[1;32m    571[0m kwds_defaults [38;5;241m=[39m _refine_defaults_read(
[1;32m    572[0m     dialect,
[1;32m    573[0m     delimiter,
[0;32m   (...)[0m
[1;32m    582[0m     defaults[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mdelimiter[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m,[39m[38;5;124m"[39m},
[1;32m    583[0m )
[1;32m    584[0m kwds[38;5;241m.[39mupdate(kwds_defaults)
[0;32m--> 586[0m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py:482[0m, in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    479[0m _validate_names(kwds[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mnames[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m))
[1;32m    481[0m [38;5;66;03m# Create the parser.[39;00m
[0;32m--> 482[0m parser [38;5;241m=[39m [43mTextFileReader[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m    484[0m [38;5;28;01mif[39;00m chunksize [38;5;129;01mor[39;00m iterator:
[1;32m    485[0m     [38;5;28;01mreturn[39;00m parser

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py:811[0m, in [0;36mTextFileReader.__init__[0;34m(self, f, engine, **kwds)[0m
[1;32m    808[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m [38;5;129;01min[39;00m kwds:
[1;32m    809[0m     [38;5;28mself[39m[38;5;241m.[39moptions[[38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m] [38;5;241m=[39m kwds[[38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m]
[0;32m--> 811[0m [38;5;28mself[39m[38;5;241m.[39m_engine [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_engine[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mengine[49m[43m)[49m

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/io/parsers/readers.py:1040[0m, in [0;36mTextFileReader._make_engine[0;34m(self, engine)[0m
[1;32m   1036[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1037[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mUnknown engine: [39m[38;5;132;01m{[39;00mengine[38;5;132;01m}[39;00m[38;5;124m (valid options are [39m[38;5;132;01m{[39;00mmapping[38;5;241m.[39mkeys()[38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m"[39m
[1;32m   1038[0m     )
[1;32m   1039[0m [38;5;66;03m# error: Too many arguments for "ParserBase"[39;00m
[0;32m-> 1040[0m [38;5;28;01mreturn[39;00m [43mmapping[49m[43m[[49m[43mengine[49m[43m][49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mf[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moptions[49m[43m)[49m

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py:51[0m, in [0;36mCParserWrapper.__init__[0;34m(self, src, **kwds)[0m
[1;32m     48[0m kwds[[38;5;124m"[39m[38;5;124musecols[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39musecols
[1;32m     50[0m [38;5;66;03m# open handles[39;00m
[0;32m---> 51[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open_handles[49m[43m([49m[43msrc[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m
[1;32m     52[0m [38;5;28;01massert[39;00m [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m     54[0m [38;5;66;03m# Have to pass int, would break tests using TextReader directly otherwise :([39;00m

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py:222[0m, in [0;36mParserBase._open_handles[0;34m(self, src, kwds)[0m
[1;32m    218[0m [38;5;28;01mdef[39;00m [38;5;21m_open_handles[39m([38;5;28mself[39m, src: FilePathOrBuffer, kwds: [38;5;28mdict[39m[[38;5;28mstr[39m, Any]) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m    219[0m     [38;5;124;03m"""[39;00m
[1;32m    220[0m [38;5;124;03m    Let the readers open IOHandles after they are done with their potential raises.[39;00m
[1;32m    221[0m [38;5;124;03m    """[39;00m
[0;32m--> 222[0m     [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;241m=[39m [43mget_handle[49m[43m([49m
[1;32m    223[0m [43m        [49m[43msrc[49m[43m,[49m
[1;32m    224[0m [43m        [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m    225[0m [43m        [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mencoding[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[1;32m    226[0m [43m        [49m[43mcompression[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mcompression[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[1;32m    227[0m [43m        [49m[43mmemory_map[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mmemory_map[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m[43m,[49m
[1;32m    228[0m [43m        [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mstorage_options[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[1;32m    229[0m [43m        [49m[43merrors[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mencoding_errors[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mstrict[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m,[49m
[1;32m    230[0m [43m    [49m[43m)[49m

File [0;32m/usr/local/lib/python3.8/site-packages/pandas/io/common.py:641[0m, in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    639[0m [38;5;28;01mif[39;00m is_path:
[1;32m    640[0m     [38;5;28;01massert[39;00m [38;5;28misinstance[39m(handle, [38;5;28mstr[39m)
[0;32m--> 641[0m     handle [38;5;241m=[39m [43mgzip[49m[38;5;241;43m.[39;49m[43mGzipFile[49m[43m([49m
[1;32m    642[0m [43m        [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mhandle[49m[43m,[49m
[1;32m    643[0m [43m        [49m[43mmode[49m[38;5;241;43m=[39;49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m,[49m
[1;32m    644[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcompression_args[49m[43m,[49m
[1;32m    645[0m [43m    [49m[43m)[49m
[1;32m    646[0m [38;5;28;01melse[39;00m:
[1;32m    647[0m     handle [38;5;241m=[39m gzip[38;5;241m.[39mGzipFile(
[1;32m    648[0m         [38;5;66;03m# error: Argument "fileobj" to "GzipFile" has incompatible type[39;00m
[1;32m    649[0m         [38;5;66;03m# "Union[str, Union[IO[Any], RawIOBase, BufferedIOBase, TextIOBase,[39;00m
[0;32m   (...)[0m
[1;32m    653[0m         [38;5;241m*[39m[38;5;241m*[39mcompression_args,
[1;32m    654[0m     )

File [0;32m/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/gzip.py:173[0m, in [0;36mGzipFile.__init__[0;34m(self, filename, mode, compresslevel, fileobj, mtime)[0m
[1;32m    171[0m     mode [38;5;241m+[39m[38;5;241m=[39m [38;5;124m'[39m[38;5;124mb[39m[38;5;124m'[39m
[1;32m    172[0m [38;5;28;01mif[39;00m fileobj [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 173[0m     fileobj [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mmyfileobj [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[43m [49m[38;5;129;43;01mor[39;49;00m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    174[0m [38;5;28;01mif[39;00m filename [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    175[0m     filename [38;5;241m=[39m [38;5;28mgetattr[39m(fileobj, [38;5;124m'[39m[38;5;124mname[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m'[39m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './all-lprs.csv.gz'
FileNotFoundError: [Errno 2] No such file or directory: './all-lprs.csv.gz'

